### ISSUE TITLE
📝 Note that routes file is optional

### ISSUE THREAD

**Issue by CollierCZ** [platformsh/platformsh-docs#2442]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/configuration/routes.html
And wherever there are notes about what files are necessary.

### What exactly should be updated?

For projects with only 1 app, the `.platform/routes.yaml` will be optional. It will default to something like the following:
```yaml
"https://{default}/":
    type: upstream
    upstream: "<name of the application>:http"
```
