### ISSUE TITLE
Configuration file did not validate

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#2529]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/create-apps/web/custom-headers.html#cross-origin-requests

### What exactly should be updated?

Hi team, 
I just try to add this piece of code from this page :

```
web:
    locations:
        "/":
            ...
            # Apply rules to all static files (dynamic files get rules from your app)
            headers:
                Access-Control-Allow-Origin: *
```
but it did not validate because of the missing " , it should be :
```
                Access-Control-Allow-Origin: "*"
```

### Additional context

error from validation is 
```
Validating configuration files

E: Error parsing configuration files:
    - applications./admin/.platform.app.yaml: Error loading data: while scanning an alias
          in "/admin/.platform.app.yaml", line 32, column 44
        did not find expected alphabetic or numeric character
```
