### ISSUE TITLE
📝 Improve clarity on websockets

### ISSUE THREAD

**Issue by trolologuy** [platformsh/platformsh-docs#2603]
### Where on docs.platform.sh should be changed?

Create something to describe connecting to websockets

### What exactly should be updated?

The [doc on sockets](https://docs.platform.sh/define-routes.html#websocket-routes) doesn't provide guidance on how to connect to these sockets.
How does one go about connecting to it?
Does it need a $PORT?

Probably create something elsewhere to describe connection and link it in the route page (and from there).

### Additional context

See also [question on Stack Overflow](https://stackoverflow.com/questions/74180005/how-to-setup-ratchet-websocket-server-for-production-for-symfony-6-app-on-platfo)

**Comment by matthiaz** [comment]
in .platform.app.yaml it should have something like this
```

web:
  commands:
    start: /app/.linuxbrew/bin/websocketd --port=$PORT ./wsmanager.sh
  upstream:
    socket_family: tcp
    protocol: http
  locations:
    '/':
      passthru: true
      request_buffering:
        enabled: false
```

In routes something weird is going on.

I had to put 2 routes https AND http, because if I only put https, I get an autoredirect to http, which obviously won't work with every websocket client.

```
"https://{default}/ws":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: false
"http://{default}/ws":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: false
```

So... does it need _just_ http:// or... is something buggy? Would even make a little more sense to have this as ws:// and wss:// in stead. (not sure if we even support wss?)

**Comment by CollierCZ** [comment]
`wss`/`ws` isn't supported in `routes.yaml`. I believe it's converted automatically to a websocket.

I'm not sure the routes doc is the appropriate place for describing connections themselves.

**Comment by matthiaz** [comment]
ok, fair enough, maybe a separete section? 
We can then also add "how to set up a secure wss connection"

**Comment by chadwcarlson** [comment]
```yaml
"https://{default}/ws":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: false

# Below http config may not be necessary for every websocket client.
"http://{default}/ws":
    type: upstream
    upstream: "app:http"
    cache:
        enabled: false
```
