### ISSUE TITLE
Document Rust runtime

### ISSUE THREAD

**Issue by AnouckColson** [platformsh/platformsh-docs#2977]
### What needs to be documented?

We need a dedicated page in https://docs.platform.sh/languages.html to document the new Rust runtime as an Alpha version => to attract testers and therefore get real user feedback. See context for additional info.

**Comment by chadwcarlson** [comment]
`.platform.app.yaml`

```yaml
# The app's name, which must be unique within the project.
name: 'app'

# The language and version for your app.
type: 'rust:1'

# The size of the app's persistent disk (in MB).
disk: 2048


hooks:
  build:
    cargo build

web:
  commands:
      start: './target/debug/hello'
```
