### ISSUE TITLE
Latest version of Poetry broken for builds

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#2983]
### Where on docs.platform.sh should be changed?

When using the latest version of Poetry, the current configuration no longer works. This relates to the Python dependencies page, and the Django guide currently. 

### What exactly should be updated?

Configuration should be adjusted to the following:

```yaml
variables:
    env:
        POETRY_VERSION: 1.4.0       
        POETRY_VIRTUALENVS_IN_PROJECT: true
        POETRY_VIRTUALENVS_CREATE: true
        POETRY_INSTALLER_MAX_WORKERS: 10
```

Previously VirtualEnvsCreate = false was necessary, now it causes a failure.
