### ISSUE TITLE
Vendor: CLI vars

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#3473]
### Where on docs.platform.sh should be changed?

- All variables will continue to use `PLATFORM_` prefix
- Except for CLI vars, which need to be changed to `UPSUN_` from `PLATFORMSH_`

### What exactly should be updated?

Quickest way to update + handle the fact that they're not the same:

1. Add a new vendor parameter

```yaml
vendor:
    name: Upsun
    cli: upsun
    altname: upsun
    env_prefix: PLATFORM
    cli_prefix: UPSUN
```

2. Add a new shortcode `themes/psh-docs/layouts/shortcodes/vendor/prefix_cli`

```
{{ .Site.Params.vendor.cli_prefix }}
```
