### ISSUE TITLE
Relationships: hash map, property keys, and default values

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#3522]
### Where on docs.platform.sh should be changed?

- https://docs.platform.sh/create-apps/app-reference.html#relationships
- https://docs.platform.sh/add-services/elasticsearch.html#example-configuration, for all service pages

### What exactly should be updated?

Git 24 replaces the <service_name>:<endpoint_name> string by a more intuitive hash map. The value of the relationship is now expected to have up to 2 sub-properties:

```yaml
relationships:
    service: mariadb_database
    endpoint: mysql
```

In replacement for

```yaml
relationships:
    mariadb_database: "mariadb_database:mysql"
```

Relationship declarations have been simplified and have now default values. For example, if you declared the following services:

```yaml
services:
    mariadb_database:
        type: mariadb:10.11

    cache:
        type: redis:6
```

You can simply use this in your relationships:

```yaml
relationships:
    mariadb_database:
    cache:
```

Instead of the more verbose:

```yaml
relationships:
    mariadb_database:
        service: mariadb_database
        endpoint: mysql

    redis_database:
        service: redis
        endpoint: redis
```

This simplification will be available on all projects, the legacy notation is still supported and documented.
