### ISSUE TITLE
Cron configuration changes

### ISSUE THREAD

**Issue by alexthunder3** [platformsh/platformsh-docs#3935]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/create-apps/app-reference/single-runtime-image.html#cron-commands

### What exactly should be updated?

Not sure since when, but the cron configuration used to be like:
```
crons:
    name:
        spec: ' * * * * *'
        cmd: 'echo hello'
```
but I found the following version in a project using a fresher psh template:
```
crons:
    name:
        spec: ' * * * * *'
        commands: 
            start: 'echo hello'
```

which I originally thought is wrong, but after checking psh template and docs, looks like the correct version. 
So what I am currently missing right now and would love to have available in the docs is:
- the "old way" seems to still work, but will this work forever or will it be deprecated at some point?

Thanks!
