### ISSUE TITLE
Fix `crons` documentation

### ISSUE THREAD

**Issue by ralt** [platformsh/platformsh-docs#412]
The [current documentation](https://docs.platform.sh/configuration/app-containers.html#crons--cronjobs) lets one think that this is valid:

```
crons:
    spec: ...
    cmd: ...
```

While in reality, this is necessary:

```
crons:
    foo:
        spec: ...
        cmd: ...
```

Where `foo` is the name of the cron.
