### ISSUE TITLE
Add clarification: PHP settings via `variables.php`

### ISSUE THREAD

**Issue by chadwcarlson** [platformsh/platformsh-docs#4162]
### Where on docs.platform.sh should be changed?

- https://docs.platform.sh/languages/php.html#php-settings
- https://docs.upsun.com/languages/php.html#php-settings

### What exactly should be updated?

Update the above pages so there is no confusion that PHP settings can be set using `app_name.variables.php`. One idea would be to replicate the table shown (and each value's defaults) using this syntax.

```yaml
variables:
  php:
    'max_execution_time': 300
    'max_file_uploads': 20
    'max_input_time': 60
    'max_input_vars': 1000
    'memory_limit': '128M'
    'post_max_size': '64M'
    'zend.assertions': -1
    'opcache.memory_consumption': 64
    'opcache.validate_timestamps': 0
```
