### ISSUE TITLE
Update comment on PR workflow to only run if the depending workflow succeeds

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformsh-docs#4405]
### Where on docs.platform.sh should be changed?

N/A

### What exactly should be updated?

The `Comment on PR` workflow is triggered via completion of the `Get PR URL, start dependent jobs` workflow. There are scenarios where that workflow can fail. We need to update the job in the `Comment on PR` workflow to only run if `Get PR URL, start dependent jobs` workflow runs conclusion is `success`. 

```
name: Comment on PR
on:
  workflow_run:
    workflows: ["Get PR URL, start dependent jobs"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      - uses: actions/checkout@v2
<snip>
```
