### ISSUE TITLE
clarification on when "require" is required in dependencies

### ISSUE THREAD

**Issue by gilzow** [platformsh/platformsh-docs#4591]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/languages/php.html#alternative-repositories
https://docs.upsun.com/languages/php.html#alternative-repositories 

### What exactly should be updated?

in both docs, we show an example of 

```
    dependencies:
      php:
        composer/composer: '^2'
        require:
          "platformsh/client": "2.x-dev"
        repositories:
          - type: vcs
            url: "git@github.com:platformsh/platformsh-client-php.git"
```
ie

```
    dependencies:
      php:
        require:
          "platformsh/client": "2.x-dev"
           composer/composer: '^2'
        repositories:
          - type: vcs
            url: "git@github.com:platformsh/platformsh-client-php.git"
```

(indentation differs between the two). In both, we all dependencies need to be placed under `require`. 

### Additional context

This is related, but may require its own issue. 

> when the `require` property is used we have a switch where the block is dump the a .globlal/composer.json on the container

This means other areas of composer config are possible to be added and used in this global composer section of the configuration file. For example, if one of your dependencies is a plugin, you need to mark that plugin as being allowed. By using `require` we can have the `config` section included:

```
dependencies:
  php:
    require:
        composer/composer: '2.6.6'
        symfony/runtime: '*'
    config:
        allow-plugins:
            "symfony/runtime": "true"
```
