### ISSUE TITLE
PHP tuning page needs love

### ISSUE THREAD

**Issue by flovntp** [platformsh/platformsh-docs#4630]
### Where on docs.platform.sh should be changed?

https://docs.platform.sh/languages/php/tuning.html (same for Upsun?)

### What exactly should be updated?

from this [conversation on Discord](https://discord.com/channels/1121795479785721957/1284195912549404703/1377277179083362505)
It seems that tuning has change a bit: 
This is what the user needed to add: 
```
    php:
        zend_detect_unicode: 0
        session_use_strict_mode: 1
        max_execution_time: 30
        display_errors: "Off"
        display_startup_errors: "0"
```

also blackfire says that  `opcache.validate_timestamps: 0` should be `on`, 
despite the recommendation from psh that says it should be `off`
